use SKILL;
DROP TABLE if exists SKILL.Users;
DROP TABLE if exists SKILL.Afval;
DROP TABLE if exists SKILL.AfvalType;

CREATE TABLE SKILL.AfvalType(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    type VARCHAR(255) NOT NULL,
    gewicht INT NOT NULL,
    tijd DATETIME NOT NULL UNIQUE
);
CREATE TABLE SKILL.Afval(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,

    CONSTRAINT afval_id_foreign FOREIGN KEY(id) REFERENCES AfvalType(id)
);
CREATE TABLE SKILL.Users(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    userName VARCHAR(255) NOT NULL UNIQUE,
    score BIGINT NULL,
    administrator BOOLEAN NOT NULL,

    CONSTRAINT users_id_foreign FOREIGN KEY(id) REFERENCES Afval(id)
);




