use SKILL;
DROP TABLE if exists SKILL.Afval;
DROP TABLE if exists SKILL.Users;
DROP TABLE if exists SKILL.AfvalType;

CREATE TABLE SKILL.AfvalType(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  type VARCHAR(255) NOT NULL,
  gewicht INT NOT NULL,
  tijd DATETIME NOT NULL
);
CREATE TABLE SKILL.Users(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    userName VARCHAR(255) NOT NULL UNIQUE,
    score BIGINT NULL,
    administrator BOOLEAN NOT NULL
);


CREATE TABLE SKILL.Afval(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  type_id INT UNSIGNED NOT NULL,
  user_id INT UNSIGNED NOT NULL,
  FOREIGN KEY (type_id) REFERENCES AfvalType(id),
  FOREIGN KEY (user_id) REFERENCES Users(id)
);

